name: booksy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^19.0.0
  google_mobile_ads: ^5.3.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
