// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCds9EEoDB5Wqa3Yd6Hwl5udrgce8OcuGU',
    appId: '1:964630629467:web:269febf87215ebb1bbc37e',
    messagingSenderId: '964630629467',
    projectId: 'booksy-app-54cd3',
    authDomain: 'booksy-app-54cd3.firebaseapp.com',
    storageBucket: 'booksy-app-54cd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAetZJg3La1Ex9xG-VR-7IMsYjUIfRsD1Y',
    appId: '1:964630629467:android:6eda59767b2e6f5dbbc37e',
    messagingSenderId: '964630629467',
    projectId: 'booksy-app-54cd3',
    storageBucket: 'booksy-app-54cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4yprX4MHLwtgmDUHquPUKYCOdQreMWg',
    appId: '1:964630629467:ios:d97bf3acea87235fbbc37e',
    messagingSenderId: '964630629467',
    projectId: 'booksy-app-54cd3',
    storageBucket: 'booksy-app-54cd3.firebasestorage.app',
    iosBundleId: 'com.example.booksyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ4yprX4MHLwtgmDUHquPUKYCOdQreMWg',
    appId: '1:964630629467:ios:d97bf3acea87235fbbc37e',
    messagingSenderId: '964630629467',
    projectId: 'booksy-app-54cd3',
    storageBucket: 'booksy-app-54cd3.firebasestorage.app',
    iosBundleId: 'com.example.booksyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCds9EEoDB5Wqa3Yd6Hwl5udrgce8OcuGU',
    appId: '1:964630629467:web:1d64aff9a4920fffbbc37e',
    messagingSenderId: '964630629467',
    projectId: 'booksy-app-54cd3',
    authDomain: 'booksy-app-54cd3.firebaseapp.com',
    storageBucket: 'booksy-app-54cd3.firebasestorage.app',
  );
}
